### ISSUE TITLE
(Python-mode) puni-backward-delete-char (delete/backspace) result in error if used in certain string with escaped characters

### ISSUE THREAD

**Issue by Inc0n** [AmaiKinono/puni#34]
This issue is specifically found whilst editing a python file
```
    return fortune_files[randomBook] + ':\n' + fortune[randomRecord].strip() + '\n'|
```
Again, | indicates the position of the cursor, 
1. press `delete` once, cursor delets into the string, i.e. cursor after character n
2. press `delete` again, cursor deletes character n
3. press `delete` for 3rd time, error signalled.

This was the specific line of code that had the error, I tried to hack up some other example issues such as the following, which worked fine:
```
print('hello world\n'|)
```

Here is the full log:
```
Debugger entered--Lisp error: (cl-assertion-failed ((>= string-start last-string-end) "Overlapping strings detected (start=%d, last-end=%..." 4219 4230))
  cl--assertion-failed((>= string-start last-string-end) "Overlapping strings detected (start=%d, last-end=%..." (4219 4230) nil)
  python-nav-end-of-statement()
  python-info-end-of-statement-p()
  python-info-end-of-block-p()
  python-nav--forward-sexp(-1 nil nil)
  python-nav-forward-sexp(-1)
  forward-sexp(-1)
  puni--forward-sexp-wrapper(-1)
  puni--primitive-backward-sexp()
  puni--strict-primitive-forward-sexp()
  puni--strict-primitive-forward-sexp-in-thing(puni--in-string-p "string")
  puni-strict-forward-sexp-in-string()
  puni-strict-forward-sexp()
  puni-region-balance-p(4152 4151 nil)
  puni-soft-delete(4152 4151 nil nil nil nil)
  puni-soft-delete-by-move(backward-char)
  puni-backward-delete-char(1)
  funcall-interactively(puni-backward-delete-char 1)
  call-interactively(puni-backward-delete-char nil nil)
  command-execute(puni-backward-delete-char)
```
I have additionally realised, that this perhaps is an issue caused by the sexp structure of how python works rather than that of puni, such that, after delete the character `n`: presing `C-M-f` results in the error described earlier in the first example, whilst `C-M-b` does nothing. In the second the example, `C-M-b` results in that error, whilst `C-M-f` does nothing.

Regardless, I would like to hear some takes from more experienced users, from them on to take the best course of action.

**Comment by Inc0n** [comment]
As of now, puni-force-delete (C-c del) could be used once the character n is deleted, to delete the backslash.

**Comment by AmaiKinono** [comment]
I can't reproduce this. What I did is:

1. paste this line into the `*scratch*` buffer:

   ```python
       return fortune_files[randomBook] + ':\n' + fortune[randomRecord].strip() + '\n'
   ```

2. `M-x python-mode`.

3. Goto end of line and press `DEL`. On the 3rd time I didn't get an error, but

   ```python
       return fortune_files[randomBook] + ':\n' + fortune[randomRecord].strip() + '
   ```

   The `\'` part is deleted.

`python-mode`is a built-in package, and I'm using Emacs 28.1, which may not be the same version you use. This may be the reason of different behavior on my side.

A minimal example may be:

```python
a = '' + '\|'
```

The cause of the problem (on my side) is: if we call `backward-sexp`, we get:

```python
a = '' + '|\'
```

If we then call `forward-sexp`, we get:

```python
a = '' + '\'|
```

So puni thinks `\'` is a balanced sexp. As `\` and `'` are not part of a symbol, puni thinks they are the opening and ending delimiters of that sexp. The fact `backward-sexp` can move the cursor out of the opening delimiter is a common misbehavior of many major modes, so that doesn't contradicts with the conclusion that `\'` is a sexp.

So when the cursor is inside the `\'`, pressing `DEL` will delete the whole sexp, just as pressing `DEL` in `(|)` will delete the whole sexp.

To me, the root cause is in `python-mode`, not in puni:

```python
## Wrong behavior
a = '' + '|\'
# call `forward-sexp`
a = '' + '\'|

## Right behavior
a = '' + '|\'
# call `forward-sexp`
a = '' + '\|'
```

Puni is built on a bag of heuristics, which aims to fix misbehaviors of `forward-sexp-function` of various major modes. There's no way it can fix all of them, so problems like this happen time to time. I personally bind `puni-force-delete` to `C-h`, which (as you've realized) is useful when this happens, and `C-h` is is the shortcut in terminals to kill a char backward.

**Comment by Inc0n** [comment]
Fair enough, thanks for the time taken on this issue.
