### ISSUE TITLE
Puni commands does not respect numeric arguments

### ISSUE THREAD

**Issue by terlar** [AmaiKinono/puni#5]
I noticed that puni commands does not respect numeric arguments (for example: C-u 3 M-d should kill 3 words).

https://www.gnu.org/software/emacs/manual/html_node/elisp/Prefix-Command-Arguments.html

It would be great if all the puni commands could retain this behavior.

Standard command overrides that should have support to avoid unexpected behavior:
- `puni-forward-delete-char`
- `puni-backward-delete-char`
- `puni-forward-kill-word`
- `puni-backward-kill-word`
- `puni-kill-line` (backward kill line can be achieved via this command when provided with C-u 0 or even multiple lines with C-u -3)
- `puni-forward-sexp`
- `puni-backward-sexp`
- `puni-beginning-of-sexp`
- `puni-end-of-sexp`

New commands that would be nice to support numeric arguments as well:
- `puni-syntactic-forward-punct`
- `puni-syntactic-backward-punct`

I might have missed something. But these are the ones I noticed and also reading through the README to see what commands are provided.

**Comment by AmaiKinono** [comment]
Thanks. I'll look into this.

Personally I never use prefix arguments.

**Comment by AmaiKinono** [comment]
Implemented :D

Also, some built-in options are supported, like `delete-active-region`.

**Comment by terlar** [comment]
Thank you very much, that was very quick! I will take it for a spin :dancers:

**Comment by AmaiKinono** [comment]
@terlar though this is off-topic, but what are some smartparens commands that you like, and are not implemented by Puni?

I'm asking because I added a `puni-up-list` API. It allows us to do some magic things, like slurp:

![9376b2ea9283b7d86e0fb2510e8b4ce0a4a5230e](https://user-images.githubusercontent.com/28714352/130117708-a71ba06c-fd9e-4f52-8ed6-e16deb521690.gif)

barf, splice, raise and split can all be implemented using the same technique, so I'm thinking seriously about replacing smartparens completely ;)

**Comment by terlar** [comment]
Thank you for asking, I am on the same journey, switched to Puni, `show-paren-mode` and `electric-pair-mode` yesterday and so far this is the only config that remains for the smartparens package now:

```
(use-package smartparens
  :ensure t
  :general
  ("M-'" 'sp-change-inner
   "M-C" 'sp-clone-sexp
   "M-D" 'sp-unwrap-sexp
   "M-R" 'sp-rewrap-sexp
   "M-W" 'sp-wrap-round))
```

Except for those I don't miss anything else from smartparens that I know of. I know that barf, splice, raise and split can be really powerful, but never found nice keybindings for them to make them part of my workflow.

I encourage you to follow up on this, although it was nice to avoid the smartparens based modes, it would be nice to get rid of it since now my use is so small. Actually I was searching a bit yesterday to see if there were any packages that solved these things. I only found https://github.com/clemera/objed but that is a quite different beast.

**Comment by AmaiKinono** [comment]
Thanks. Allow me to comment on these:

- `sp-change-inner`: I think this is impossible with Puni, as I haven't find a way to implement `down-list`, so we can't go in a sexp. If you could manually go in the next sexp, then we have plenty ways doing it. Possible ways:
  - `puni-beginning-of-sexp`, set mark, `puni-end-of-sexp`, delete. You can also put them into a command.
  - `expand-region`: https://github.com/AmaiKinono/puni/wiki/The-Puni-version-of-expand-region
  - Use `my-kill-line` [here](https://github.com/AmaiKinono/puni/wiki/Useful-commands#a-smarter-kill-line) and press `C-k` twice.

- `sp-clone-sexp`: this is doable.

- `sp-unwrap-sexp`: I think this can be replaced by splice. Also, unwrap the sexp after point is hard to do because we don't have `down-list`. We can only unwrap the sexp around point.

- `sp-rewrap-sexp`: doable. But I'm thinking people may want to replace a pair of html tags using this...

- `sp-wrap-round`: doable. But I might prefer mark the sexp first, then press `(`.

**Comment by terlar** [comment]
All fair, I will try to experiment with these suggestions. Agree with HTML tags, that sounds like it will be quite tricky and no standard way to do it.

BTW it seems `puni-kill-line` is not working quite correct with the numeric prefix.

If I use `C-u 2` it only removes one line and if I use `C-u 3` it removes two lines and leaves a blank line. First I do the operations with the builtin `C-u 2 C-k`, then `C-u 3 C-k`, then I switch to Puni and do the same.

![Kooha-2021-08-19-22:47:55](https://user-images.githubusercontent.com/280235/130142221-eea061cd-4b59-49d4-abb6-9f22876b0c3f.gif)

Here are screenshots of the same:

Original state:
![emacs-M2-before](https://user-images.githubusercontent.com/280235/130142389-77e657cd-5116-456d-93b0-5beb4cbcd2a3.png)

After Emacs `C-u 2 C-k`:
![emacs-M2-after](https://user-images.githubusercontent.com/280235/130142409-37feed99-1aa0-45d3-8f55-263df07e20da.png)

After Puni `C-u 2 C-k`:
![puni-M2-after](https://user-images.githubusercontent.com/280235/130142512-ab3edb2c-fb0c-4f25-9be0-21eb4c25d53f.png)

After Emacs `C-u 3 C-k`:
![emacs-M3-after](https://user-images.githubusercontent.com/280235/130142589-afaa92c7-33b6-4308-8afb-5cf79c8344d9.png)

After Puni `C-u 3 C-k`:
![puni-M3-after](https://user-images.githubusercontent.com/280235/130142605-686d150f-9287-43e2-ba02-20c3a0726835.png)

**Comment by AmaiKinono** [comment]
Thanks. I'll look into this.

**Comment by AmaiKinono** [comment]
I've fixed them, please test.

Also, I think the behavior of `kill-line` on zero or negative prefix arg is pretty dumb. `puni-kill-line` (with negative arg) and `puni-backward-kill-line` (with positive arg) have saner behavior.

**Comment by terlar** [comment]
Thank you, seems to work correctly now, I will use this more and notify if I run into something strange.

I do have some things, but I think that is things related to the SMIE implementation for the language I'm using.

**Comment by AmaiKinono** [comment]
Could you open an issue for it? Even if we can't find a fix, at least we can have an user option to disable re-indent for some major modes.
