### ISSUE TITLE
`puni-kill-line` misbehaving after 518a5362870b6ef01d2d4a158bd38c7280687256

### ISSUE THREAD

**Issue by tsdh** [AmaiKinono/puni#64]
I have a buffer (with `text-mode` or even `fundamental-mode` with this text.

```
|This is a sentence.  This is another one.  Together, we are the whole
paragraph.  This is a sentence.  This is another one.  Together, we are the
whole paragraph.  This is a sentence.  This is another one.  Together, we are
the whole paragraph.  This is a sentence.  This is another one.  Together, we
are the whole paragraph.
```

The `|` represents point.  I hit `C-k` twice (`puni-kill-line`).  I end up with this:

```
        |paragraph.  This is a sentence.  This is another one.  Together, we are the
whole paragraph.  This is a sentence.  This is another one.  Together, we are
the whole paragraph.  This is a sentence.  This is another one.  Together, we
are the whole paragraph.
```

Why does it indent point?  I guess that's an unwanted side-effect of 518a5362870b6ef01d2d4a158bd38c7280687256.

Also `puni-kill-line` at the end of the buffer repeatedly inserts more spaces.

(I've originally added that observation to #16 but that's already closed and I cannot re-open, so I'm filing a new issue.)

**Comment by AmaiKinono** [comment]
Should be fixed, please test.

**Comment by tsdh** [comment]
Yes, works fine again.  Thanks a lot!

**Comment by montchr** [comment]
I'm actually running into this behavior on the latest commit (f430f5b).  #68 looks similar, but the before/after examples in this issue are definitely the same as what I'm seeing.  Why would the issue have come back?  

If it matters, I have seen this behavior regardless of the value of `kill-whole-line`.

Here's another example, this time in `nix-ts-mode`, though I see it in quite a few other modes (I think also `php-ts-mode`):

Original, where `|` represents point:

```nix
{
  services.kanshi.settings = [
    {
      output.criteria = "eDP-1";
      |output.scale = 2.0;
    }
  ];
}
```

After first `puni-kill-line` invocation, with `|` as point:

```nix
{
  services.kanshi.settings = [
    {
      output.criteria = "eDP-1";
      |
    }
  ];
}
```

After second `puni-kill-line` invocation:

```nix
{
  services.kanshi.settings = [
    {
      output.criteria = "eDP-1";
      |}
  ];
}
```

And here's an even more minimal example in two steps:

```nix
[
  {}
  |
]
```

```nix
[
  {}
  |]
```

Please let me know if I should open another issue instead of continuing the conversation here.
